baseURL = "https://adharshkamath.github.io/"
languageCode = "en-us"
title = "Functional Curiosity"
paginate = 5
enableRobotsTXT = true
canonifyURLs = true

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
summaryLength = 30

googleAnalytics = "UA-167549289-5"

[markup.goldmark.renderer]
	unsafe= true

[permalinks]
    post = "/posts/:title/"

[params]
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
	mode = "light"
	customJS = ["https://code.jquery.com/jquery-3.5.1.min.js"]
	favicon = "/favicon.ico"
	description = "This is Adharsh's personal website where he writes articles about Programming languages, Parallel and distributed computing, and pretty much anything on earth that's interesting"
  	images = ["apple-touch-icon.png"]
  	title = "Functional Curiosity"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/adharshkamath"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/adharshkamath"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/in/adharshkamath"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://instagram.com/adharshkamath"

[[redirects]]
	from = "/*"
	to = "/404/"
	status = 404

[taxonomies]
   tag = "tags"

[author] 
	name = "Adharsh Kamath"
	email = "adharshkamathr@gmail.com"