baseURL = "https://adharshkamath.github.io/"
languageCode = "en-us"
title = "Adharsh Kamath"
paginate = 5

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

summaryLength = 20

[params]
	subtitle = "Blog and Personal website"
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
	mode = "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["https://code.jquery.com/jquery-3.4.1.js", "js/custom1.js"]  # Custom JS scripts.

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/adharshkamath"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/adharshkamath"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/in/adharshkamath"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://instagram.com/adharshkamath"

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:adharshkamathr@gmail.com"

[taxonomies]
   tag = "tags"
